---
title: New School Corporate Partnerships
timezone: UTC
collections:
  case-studies:
    title: Case Studies
    output: true
  future:
    title: Imagine the Future of…
    output: false
  schools:
    title: Our Schools
    output: false
    introduction: Our unique structure provides the expertise of five schools collaborating
      to reinvent everything and approach issues from multiple, integrated perspectives.
  people:
    title: People
    output: false
  posts:
    title: Posts
    output: true
  values:
    title: The New School is Different by Design
    output: false
  uploads:
    title: Uploads
    output: false
email: your-email@domain.com
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: 
url: http://yourdomain.com
introduction: The New School, in NYC, is the only university where a world-renowned
  art and design school comes together with acclaimed liberal arts, performing arts,
  and graduate schools…to rethink everything.
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
exclude:
- node_modules
- scss
- bower_components
