---
title: New School Corporate Partnerships
timezone: UTC
collections:
  partner:
    title: Are you ready to design the future?
    output: false
    introduction: Our partners understand the value of using design thinking to solve
      real-world problems. Collaborate with us to design the&nbsp;future.
  future:
    title: Imagine the Future of…
    output: false
  schools:
    title: One University, Five Schools
    output: false
    introduction: Our unique structure provides the expertise of five schools collaborating
      to reinvent everything and approach issues from multiple, integrated&nbsp;perspectives.
  people:
    title: Our History of Innovation
    output: false
    introduction: From our beginning in 1919, we've been a home for industry pioneers,
      world changers, and innovative leaders. Browse through a small selection of
      our exceptional alumni, students, and faculty, past and&nbsp;present.
  projects:
    title: Our Multi-Dimensional Approach
    output: false
    introduction: We connect multiple disciplines to find unforeseen opportunities
      and create unexpected possibilities for our&nbsp;partners.
    programs:
    - INTERIOR DESIGN
    - FASHION DESIGN AND SOCIETY
    - ANTHROPOLOGY
    - TRANSDISCIPLINARY DESIGN
    - SCREENWRITING
    - SUSTAINABILITY STRATEGIES
    - CONTEMPORARY MUSIC
    - INTERNATIONAL AFFAIRS
    - CULTURAL THEORY
    - HISTORICAL STUDIES
    - INTERDISCIPLINARY SCIENCE
    - ART, MEDIA, AND TECHNOLOGY
    - CREATIVE PUBLISHING
    - ENGLISH AS A SECOND LANGUAGE
    - DATA VISUALIZATION
    - LIBERAL STUDIES
    - PHOTOGRAPHY
    - FASHION DESIGN
    - PIANO
    - DOCUMENTARY MEDIA STUDIES
    - DESIGN STUDIES
    - GLOBAL EXECUTIVE
    - MEDIA MANAGEMENT
    - PRODUCT DESIGN
    - FINE ARTS
    - CREATIVE ARTS AND HEALTH
    - LITERARY STUDIES
    - CULTURE AND MEDIA
    - PHILOSOPHY
    - INDUSTRIAL DESIGN
    - INTEGRATED DESIGN
    - HISTORY
    - CRITICAL JOURNALISM
    - DIRECTING
    - JAZZ AND CONTEMPORARY MUSIC
    - HARM REDUCTION PSYCHOTHERAPY
    - GRAPHIC AND DIGITAL DESIGN
    - ORCHESTRAL INSTRUMENTS
    - FASHION STUDIES
    - LIGHTING DESIGN
    - FILM PRODUCTION
    - COMMUNICATION DESIGN
    - CLASSICAL MUSIC
    - ACTING
    - CREATIVE WRITING
    - ARCHITECTURE
    - FOOD STUDIES
    - LIBERAL ARTS
    - MEDIA STUDIES
    - HISTORY OF DESIGN
    - PSYCHOLOGY
    - THEATER
    - POLITICS
    - ORGANIZATIONAL CHANGE MANAGEMENT
    - DRAMATIC ARTS
    - URBAN DESIGN
    - FASHION BUSINESS
    - THE ARTS
    - FASHION MARKETING
    - ECONOMICS
    - PLAYWRITING
    - DESIGN AND URBAN ECOLOGIES
    - SCREEN STUDIES
    - URBAN POLICY
    - DESIGN AND TECHNOLOGY
    - GRAPHIC DESIGN
    - CURATORIAL STUDIES
    - LEADERSHIP AND CHANGE
    - ESL + DESIGN
    - GENDER AND SEXUALITY STUDIES
    - GLOBAL STUDIES
    - ENVIRONMENTAL POLICY
    - INTERFACE DESIGN
    - STRATEGIC DESIGN MANAGEMENT
    - FASHION
    - ORGANIZATION DEVELOPMENT
    - CREATIVE PUBLISHING
    - ENVIRONMENTAL STUDIES
    - SOCIOLOGY
    - MUSICAL THEATER
    - ILLUSTRATION
    - THEORIES OF URBAN PRACTICE
    - JOURNALISM + DESIGN
    - MINORS
    - NONPROFIT MANAGEMENT
  posts:
    title: Posts
    output: true
  values:
    title: The New School is Different by Design
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: people
  values:
    image: 
    video: 
    type: 
contact:
  name: Debbie Gibb
  title: Vice President
  department: Corporate Partnerships &amp; Industry Engagement
  email: corporatepartner@newschool.edu
  phone: 212.229.5667 x3174
credits_text:
- Site Design and Development by [Familiar](http://familiar-studio.com)
- 'Photography: David Barron, BFA Photo, Michael DiVito, Carly Erickson (BFA Photo), Orlando Fernandez, Stefano Giovanni (stefanogiovannini.com), Jonathan Grassi, Hafenbar, Melissa Hom, Courtesy of the John D. and Catherine T. MacArthur Foundation, Ed Kavishe, Chad J. McNeeley, Yvette Pomerantz, Martin Seck, The New School, U.S. Navy, Scott Wynn' 
email: your-email@domain.com
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: 
url: http://yourdomain.com
introduction: The New School, in NYC, is the only university where a world-renowned
  art and design school comes together with acclaimed liberal arts, performing arts,
  and graduate schools…to rethink&nbsp;everything.
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
exclude:
- node_modules
- scripts
- scss
