---
title: New School Corporate Partnerships
timezone: UTC
collections:
  partner:
    title: Are you ready to design the future?
    output: false
    introduction: Our partners understand the value of using design thinking to solve
      real-world problems. Collaborate with us to design the&nbsp;future.
  future:
    title: Imagine the Future of…
    output: false
  schools:
    title: One University, Five Schools
    output: false
    introduction: Our unique structure provides the expertise of five schools collaborating
      to reinvent everything and approach issues from multiple, integrated&nbsp;perspectives.
  people:
    title: Our History of Innovation
    output: false
    introduction: From our beginning in 1919, we've been a home for industry pioneers,
      world changers, and innovative leaders. Browse through a small selection of
      our exceptional alumni, students, and faculty, past and&nbsp;present.
  projects:
    title: Our Multi-Dimensional Approach
    output: false
    introduction: We connect multiple disciplines to find unforeseen opportunities
      and create unexpected possibilities for our&nbsp;partners.
    programs:
    - INTERIOR DESIGN
    - FASHION DESIGN AND SOCIETY
    - ANTHROPOLOGY
    - TRANSDISCIPLINARY DESIGN
    - SCREENWRITING
    - SUSTAINABILITY STRATEGIES
    - CONTEMPORARY MUSIC
    - INTERNATIONAL AFFAIRS
    - CULTURAL THEORY
    - HISTORICAL STUDIES
    - INTERDISCIPLINARY SCIENCE
    - ART, MEDIA, AND TECHNOLOGY
    - CREATIVE PUBLISHING
    - ENGLISH AS A SECOND LANGUAGE
    - DATA VISUALIZATION
    - LIBERAL STUDIES
    - PHOTOGRAPHY
    - FASHION DESIGN
    - PIANO
    - DOCUMENTARY MEDIA STUDIES
    - DESIGN STUDIES
    - GLOBAL EXECUTIVE
    - MEDIA MANAGEMENT
    - PRODUCT DESIGN
    - FINE ARTS
    - CREATIVE ARTS AND HEALTH
    - LITERARY STUDIES
    - CULTURE AND MEDIA
    - PHILOSOPHY
    - INDUSTRIAL DESIGN
    - INTEGRATED DESIGN
    - HISTORY
    - CRITICAL JOURNALISM
    - DIRECTING
    - JAZZ AND CONTEMPORARY MUSIC
    - HARM REDUCTION PSYCHOTHERAPY
    - GRAPHIC AND DIGITAL DESIGN
    - ORCHESTRAL INSTRUMENTS
    - FASHION STUDIES
    - LIGHTING DESIGN
    - FILM PRODUCTION
    - COMMUNICATION DESIGN
    - CLASSICAL MUSIC
    - ACTING
    - CREATIVE WRITING
    - ARCHITECTURE
    - FOOD STUDIES
    - LIBERAL ARTS
    - MEDIA STUDIES
    - HISTORY OF DESIGN
    - PSYCHOLOGY
    - THEATER
    - POLITICS
    - ORGANIZATIONAL CHANGE MANAGEMENT
    - DRAMATIC ARTS
    - URBAN DESIGN
    - FASHION BUSINESS
    - THE ARTS
    - FASHION MARKETING
    - ECONOMICS
    - PLAYWRITING
    - DESIGN AND URBAN ECOLOGIES
    - SCREEN STUDIES
    - URBAN POLICY
    - DESIGN AND TECHNOLOGY
    - GRAPHIC DESIGN
    - CURATORIAL STUDIES
    - LEADERSHIP AND CHANGE
    - ESL + DESIGN
    - GENDER AND SEXUALITY STUDIES
    - GLOBAL STUDIES
    - ENVIRONMENTAL POLICY
    - INTERFACE DESIGN
    - STRATEGIC DESIGN MANAGEMENT
    - FASHION
    - ORGANIZATION DEVELOPMENT
    - CREATIVE PUBLISHING
    - ENVIRONMENTAL STUDIES
    - SOCIOLOGY
    - MUSICAL THEATER
    - ILLUSTRATION
    - THEORIES OF URBAN PRACTICE
    - JOURNALISM + DESIGN
    - MINORS
    - NONPROFIT MANAGEMENT
  posts:
    title: Posts
    output: true
  values:
    title: The New School is Different by Design
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: people
  values:
    image: 
    video: 
    type: 
contact:
  name: Debbie Gibb
  title: Vice President
  department: Corporate Partnerships &amp; Industry Development
  email: corporatepartner@newschool.edu
  phone: 123-456-7890
credits_text:
- Site Design and Development by [Familiar](http://familiar-studio.com)
- 'Photo of Eleanor Roosevelt: This work is in the public domain because it was published
  in the United States between 1923 and 1963 and although there may or may not have
  been a copyright notice, the copyright was not renewed. Unless its author has been
  dead for the required period, it is copyrighted in the countries or areas that do
  not apply the rule of the shorter term for US works, such as Canada (50 pma), Mainland
  China (50 pma, not Hong Kong or Macao), Germany (70 pma), Mexico (100 pma), Switzerland
  (70 pma), and other countries with individual treaties. See Commons:Hirtle chart
  for further explanation.'
- 'Photo of Tennesee Williams: This work is from the New York World-Telegram and Sun
  collection at the Library of Congress.   According to the library, there are no
  known copyright restrictions on the use of this work. This photograph is a work
  for hire created prior to 1968 by a staff photographer at New York World-Telegram
  & Sun. It is part of a collection donated to the Library of Congress and per the
  instrument of gift it is in the public domain.Photographs in this collection other
  than those identified by such stamps as ""World-Telegram photo"" or ""World-Telegram
  photo by Ed Palumbo"" might not be in the public domain. Works within the collection
  may be attributed to other news services that retain copyright, works of the U.S.
  government that are in the public domain in the US, or works with no attribution
  for which copyright cannot be determined.'
- 'Photo of Ai WeiWei: You are free: to share – to copy, distribute and transmit the
  work to remix – to adapt the work Under the following conditions: attribution –
  You must attribute the work in the manner specified by the author or licensor (but
  not in any way that suggests that they endorse you or your use of the work). share
  alike – If you alter, transform, or build upon this work, you may distribute the
  resulting work only under the same or similar license to this one. Personality rights
  warning Although this work is freely licensed or in the public domain, the person(s)
  shown may have rights that legally restrict certain re-uses unless those depicted
  consent to such uses. In these cases, a model release or other evidence of consent
  could protect you from infringement claims. Though not obliged to do so, the uploader
  may be able to help you to obtain such evidence. See our general disclaimer for
  more information.'
- 'Photo of Bradley Cooper: This file is a work of a sailor or employee of the U.S.
  Navy, taken or made as part of that person''s official duties. As a work of the
  U.S. federal government, the image is in the public domain. Although this work is
  freely licensed or in the public domain, the person(s) shown may have rights that
  legally restrict certain re-uses unless those depicted consent to such uses. In
  these cases, a model release or other evidence of consent could protect you from
  infringement claims. Though not obliged to do so, the uploader may be able to help
  you to obtain such evidence. See our general disclaimer for more information.'
- 'Photo of Frank Lloyd Wright: This work is in the public domain because it was published
  in the United States between 1923 and 1963 and although there may or may not have
  been a copyright notice, the copyright was not renewed. Unless its author has been
  dead for the required period, it is copyrighted in the countries or areas that do
  not apply the rule of the shorter term for US works, such as Canada (50 pma), Mainland
  China (50 pma, not Hong Kong or Macao), Germany (70 pma), Mexico (100 pma), Switzerland
  (70 pma), and other countries with individual treaties. See Commons:Hirtle chart
  for further explanation.'
- 'Photo of Alexander Wang: You are free: to share – to copy, distribute and transmit
  the work to remix – to adapt the work Under the following conditions: attribution
  – You must attribute the work in the manner specified by the author or licensor
  (but not in any way that suggests that they endorse you or your use of the work).'
- 'Photo of Laura Poitras: Attribution: Courtesy of the John D. and Catherine T. MacArthur
  Foundation, You are free: to share – to copy, distribute and transmit the work to
  remix – to adapt the work Under the following conditions: attribution – You must
  attribute the work in the manner specified by the author or licensor (but not in
  any way that suggests that they endorse you or your use of the work).'
email: your-email@domain.com
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: 
url: http://yourdomain.com
introduction: The New School, in NYC, is the only university where a world-renowned
  art and design school comes together with acclaimed liberal arts, performing arts,
  and graduate schools…to rethink&nbsp;everything.
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
exclude:
- node_modules
- scss
- bower_components
- js
