---
title: New School Corporate Partnerships
timezone: UTC
collections:
  future:
    title: Imagine the Future of…
    output: false
  schools:
    title: One University, Five Schools
    output: false
    introduction: Our unique structure provides the expertise of five schools collaborating
      to reinvent everything and approach issues from multiple, integrated perspectives.
  people:
    title: Our History of Innovation
    output: false
    introduction: From our beginning in 1919, we’ve been a home for industry pioneers,
      world changers, and innovative leaders.
  projects:
    title: Our Multi-Dimensional Approach
    output: false
    introduction: We connect multiple disciplines to find unforeseen opportunities
      and create unexpected possibilities for our partners.
    programs:
    - ACTING
    - ANTHROPOLOGY
    - ARCHITECTURE
    - ART, MEDIA, AND TECHNOLOGY
    - THE ARTS
    - CLASSICAL MUSIC
    - COMMUNICATION DESIGN
    - CONTEMPORARY MUSIC
    - CREATIVE ARTS AND HEALTH
    - CREATIVE PUBLISHING
    - CRITICAL JOURNALISM
    - CREATIVE WRITING
    - CULTURE AND MEDIA
    - DATA VISUALIZATION
    - CULTURAL THEORY
    - DESIGN AND TECHNOLOGY
    - DESIGN AND URBAN ECOLOGIES
    - DESIGN STUDIES
    - DIRECTING
    - DOCUMENTARY MEDIA STUDIES
    - DRAMATIC ARTS
    - ECONOMICS
    - ENGLISH AS A SECOND LANGUAGE
    - ESL + DESIGN
    - ENVIRONMENTAL POLICY
    - FASHION BUSINESS
    - FASHION DESIGN
    - FASHION DESIGN AND SOCIETY
    - FASHION MARKETING
    - FASHION STUDIES
    - FILM PRODUCTION
    - FINE ARTS
    - FOOD STUDIES
    - GENDER AND SEXUALITY STUDIES
    - GLOBAL STUDIES
    - GRAPHIC DESIGN
    - GRAPHIC AND DIGITAL DESIGN
    - HARM REDUCTION PSYCHOTHERAPY
    - HISTORICAL STUDIES
    - HISTORY
    - HISTORY OF DESIGN
    - CURATORIAL STUDIES
    - ILLUSTRATION
    - INDUSTRIAL DESIGN
    - INTEGRATED DESIGN
    - INTERDISCIPLINARY SCIENCE
    - INTERIOR DESIGN
    - INTERNATIONAL AFFAIRS
    - JAZZ AND CONTEMPORARY MUSIC
    - JOURNALISM + DESIGN
    - LEADERSHIP AND CHANGE
    - LIBERAL ARTS
    - LIBERAL STUDIES
    - LIGHTING DESIGN
    - LITERARY STUDIES
    - MEDIA MANAGEMENT
    - MEDIA STUDIES
    - MINORS
    - MUSICAL THEATER
    - NONPROFIT MANAGEMENT
    - ORGANIZATIONAL CHANGE MANAGEMENT
    - ORGANIZATION DEVELOPMENT
    - PHILOSOPHY
    - PIANO
    - PHOTOGRAPHY
    - PLAYWRITING
    - POLITICS
    - PRODUCT DESIGN
    - PSYCHOLOGY
    - URBAN POLICY
    - SCREEN STUDIES
    - SCREENWRITING
    - SOCIOLOGY
    - INTERFACE DESIGN
    - STRATEGIC DESIGN MANAGEMENT
    - GLOBAL EXECUTIVE
    - ENVIRONMENTAL STUDIES
    - SUSTAINABILITY STRATEGIES
    - THEATER
    - THEORIES OF URBAN PRACTICE
    - TRANSDISCIPLINARY DESIGN
    - URBAN DESIGN
    - ORCHESTRAL INSTRUMENTS
  partner:
    title: Partner with Us
    output: false
    introduction: Our partners understand the value of using design thinking to solve
      real-world problems. Collaborate with us to design the future.
  posts:
    title: Posts
    output: true
  values:
    title: The New School is Different by Design
    output: false
  uploads:
    title: Uploads
    output: false
email: your-email@domain.com
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: 
url: http://yourdomain.com
introduction: The New School, in NYC, is the only university where a world-renowned
  art and design school comes together with acclaimed liberal arts, performing arts,
  and graduate schools…to rethink everything.
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
exclude:
- node_modules
- scss
- bower_components
